### ISSUE TITLE
Change namespace to `chat.llamas.cardlogic`

### ISSUE THREAD

**Issue by wodencafe** [IRC-Llamas/cardlogic#20]
This issue is for changing the source namespace / packages to use `chat.llamas.cardlogic` instead of `com.foss.llamas.poker`.

**Comment by TheDaemoness** [comment]
I have the tools to do this really easily. I'll wait until existing PRs are merged.

**Comment by wodencafe** [comment]
@TheDaemoness Do you think you could give them a review? :smile:
